sudo: required
services:
  - docker
before_script:
  - version=${TRAVIS_TAG#"v"}
  - docker pull renwei2/pytwask:latest || true
script:
  - 'cd pytwask && docker build --pull --cache-from renwei2/pytwask:latest -t renwei2/pytwask:latest .'
  - '[ ! -z "$version" ] && docker tag renwei2/pytwask:latest "renwei2/pytwask:${version}" || true'
  - docker-compose build
  - docker images
  - docker-compose up -d
  - docker ps -a
after_script:
  - docker-compose down -v
env:
  global:
  # REGISTRY_USERNAME=...
  - secure: vXCd5Bsbs8dTNd4My6wwdk2IUr1iMWY7U1JdEpXy4d9UBRv+wpBHYtkbRl2W6lFz8ADY+hd/bC0Pi9aP3LS/9rROsDjf2qWj3m30HZvOJe7rHhtrtRK+Hgrcv3MlgHUsnoH5Ew+2x6xV1JvLcPzlNew1wyS/E3Xp/6cZSlgepzSqb0YAXpQBnmAQ1HrBJezEdsOuKOnTFSgS+cQ1huW8UsGlkyGceQlZobX8HpRXFoM6vBGIUvs6uC15YYdaQf+NxkEJx1ZxYEAn46TWiVDlPZ3PEK1vaomQMFOWgjUf3Xy6UGYjuU91vyNwp49twJEayO+BrQhSTgbRvuMPBpDnBH2A1TrJExx7n3SEF8RBDo6WVJCm+/0VSqnJBTsIDHbY39MaMtYyy0QIWe/y8oUok7VAtrizmFTwenbBKMzEfkcJkW8TxKCEWCx5YrIGF3oAOUy5p8DYm9f1iSQVKYTPfoHk8gVVE0Vfb9QFxVd00PBZ7phqXIgwID/XUWLpGO3azG14pT9AdFPe368CPmnRpZfrlfn+toJA3lJ+RroEJolnQ8cU5BANMa2nj7OAoocOaN1RaO4z+04fS+FGZplupEokL3R0ddn5k8IP8CWQCCpnhc0RM9FmdiI9Enffk8EYgwxeSw1HrbrMw9JC3lqam8Trr2L1qXB/YQKtaCMC1Bw=
  # REGISTRY_PASSWORD=...
  - secure: ltZo1KVQLX4ZC0/neV7KHR57VhqrWqGWBisUHm0iOOPIX26uETEAKEHBhyv0/YbeKdgCpR9aTIipDWFFrl9iXQsDpWUOz3TM4mteSFgWNyDTXjlL+dA0qQ5hc27tbhQbIBYYiDqv6cBC06NoR/KrRG3oWNQGdx2BgKrioAZVs1nuwRkBOiD2HFvJ1gyxKTCyZ7JoD+bLDJMf+aO6m/DhqYNXZ/sdxtV3vji7r9G3X09gAIjwF9159gXfy46D4o08PNT/5TjKinI6CNrbqATyc8tJiutqd4HacpkAjfJASLpc5zWOq0KESGA4zcWcEGW8iYc2gGrgrayhsFy7nNCkmKlOWjJ2ul2VICpIPHHzobdZH9DgaHnfCbwiuJRO+5tG6V9RPRh2rW3R+fVPeYFrb05jyMYrjfx6bTwSw2GIXsZkF2UTwoagflvZ3M45nfcxUzZ9vgY+d2YBla09et4/QAqwWNSJeJ9QQXoqSDsKqTWmAhGgygTp4ZT3i+XWb1+Hl+llQWHEq9H4KtjM0ZhTv/NEsME4NJ4ks15z23LimW421/4I7CMvJS7oJLXBB5AvSJwU+aemFKQdq1sbWlCFTro/seQbxqYCUe+I4UFAVzQpNGG/UtLBMoPfNPkEuvaoD10ftUnPbcv5d7wwchHGKm/9c1SjQGFqqcdSoCkTmsk=
before_deploy:
  - 'echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USERNAME" --password-stdin'
deploy:
  provider: script
  script: 'docker push renwei2/pytwask:latest && [ ! -z "$version" ] && docker push "renwei2/pytwaks:${version}" || true'
  on:
    branch: master
